"""initial

Revision ID: 2c89aefb45bd
Revises: 
Create Date: 2026-02-26 11:09:22.921222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c89aefb45bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_type', sa.Enum('warrior', 'mage', 'rogue', 'ranger', name='classtype'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('stamina_updated_at', sa.DateTime(), nullable=False),
    sa.Column('pvp_tokens', sa.Integer(), nullable=False),
    sa.Column('pvp_tokens_reset_at', sa.DateTime(), nullable=False),
    sa.Column('pvp_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('gold >= 0', name='check_gold_non_negative'),
    sa.CheckConstraint('hp <= max_hp', name='check_hp_max'),
    sa.CheckConstraint('hp >= 0', name='check_hp_non_negative'),
    sa.CheckConstraint('level >= 1', name='check_level_min'),
    sa.CheckConstraint('pvp_rating >= 0', name='check_pvp_rating_non_negative'),
    sa.CheckConstraint('pvp_tokens >= 0', name='check_pvp_tokens_non_negative'),
    sa.CheckConstraint('stamina <= 100', name='check_stamina_max'),
    sa.CheckConstraint('stamina >= 0', name='check_stamina_non_negative'),
    sa.CheckConstraint('xp >= 0', name='check_xp_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('users')
    # ### end Alembic commands ###
