"""initial

Revision ID: 474bcce57d53
Revises: 
Create Date: 2026-03-01 13:53:29.955633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474bcce57d53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('recommended_level_min', sa.Integer(), nullable=False),
    sa.Column('recommended_level_max', sa.Integer(), nullable=False),
    sa.CheckConstraint('"order" <= 4', name='check_order_max'),
    sa.CheckConstraint('"order" >= 1', name='check_order_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_type', sa.Enum('warrior', 'mage', 'rogue', 'ranger', name='classtype'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('power_level', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('stamina_updated_at', sa.DateTime(), nullable=False),
    sa.Column('pvp_tokens', sa.Integer(), nullable=False),
    sa.Column('pvp_tokens_reset_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('gold >= 0', name='check_gold_non_negative'),
    sa.CheckConstraint('hp <= max_hp', name='check_hp_max'),
    sa.CheckConstraint('hp >= 0', name='check_hp_non_negative'),
    sa.CheckConstraint('level >= 1', name='check_level_min'),
    sa.CheckConstraint('pvp_tokens >= 0', name='check_pvp_tokens_non_negative'),
    sa.CheckConstraint('stamina <= 100', name='check_stamina_max'),
    sa.CheckConstraint('stamina >= 0', name='check_stamina_non_negative'),
    sa.CheckConstraint('xp >= 0', name='check_xp_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('weapon', 'head', 'chest', 'legs', 'offhand', 'accessory', name='itemtype'), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'uncommon', 'rare', 'epic', 'legendary', name='itemrarity'), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('defense_bonus', sa.Integer(), nullable=False),
    sa.Column('hp_bonus', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monsters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_xp_reward', sa.Integer(), nullable=False),
    sa.Column('base_gold_min', sa.Integer(), nullable=False),
    sa.Column('base_gold_max', sa.Integer(), nullable=False),
    sa.Column('order_in_zone', sa.Integer(), nullable=False),
    sa.Column('is_zone_boss', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_gold_min <= base_gold_max', name='check_base_gold_non_exceeding'),
    sa.CheckConstraint('order_in_zone <= 4', name='check_order_in_zone_max'),
    sa.CheckConstraint('order_in_zone >= 1', name='check_order_in_zone_min'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'order_in_zone', name='uq_monster_zone_order')
    )
    op.create_table('potions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('health', 'attack', name='potiontype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('combat_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('monster_id', sa.UUID(), nullable=False),
    sa.Column('monster_level', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('win', 'lose', 'flee', name='combatresult'), nullable=False),
    sa.Column('xp_gained', sa.Integer(), nullable=False),
    sa.Column('gold_gained', sa.Integer(), nullable=False),
    sa.Column('item_dropped_id', sa.UUID(), nullable=True),
    sa.Column('turns_taken', sa.Integer(), nullable=False),
    sa.Column('combat_text', sa.JSON(), nullable=False),
    sa.Column('potions_used', sa.JSON(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('damage_taken', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['item_dropped_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('equipped_slot', sa.Enum('weapon', 'head', 'chest', 'legs', 'offhand', 'accessory', name='itemtype'), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'equipped_slot')
    )
    op.create_table('monster_drops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monster_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('drop_chance', sa.Float(), nullable=False),
    sa.CheckConstraint('drop_chance <= 1', name='check_drop_chance_non_exceeding'),
    sa.CheckConstraint('drop_chance >= 0', name='check_drop_chance_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'item_id', name='uq_monster_item')
    )
    op.create_table('monster_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('monster_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp_multiplier', sa.Float(), nullable=False),
    sa.Column('attack_multiplier', sa.Float(), nullable=False),
    sa.Column('defense_multiplier', sa.Float(), nullable=False),
    sa.Column('xp_multiplier', sa.Float(), nullable=False),
    sa.Column('gold_multiplier', sa.Float(), nullable=False),
    sa.Column('drop_chance_bonus', sa.Float(), nullable=False),
    sa.CheckConstraint('level <= 5', name='check_level_max'),
    sa.CheckConstraint('level >= 1', name='check_level_min'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'level', name='uq_check_monster_level')
    )
    op.create_table('monster_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('monster_id', sa.UUID(), nullable=False),
    sa.Column('highest_level_beaten', sa.Integer(), nullable=False),
    sa.Column('total_kills', sa.Integer(), nullable=False),
    sa.CheckConstraint('highest_level_beaten <= 5', name='check_level_beaten_max'),
    sa.CheckConstraint('highest_level_beaten >= 0', name='check_level_beaten_min'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'monster_id', name='uq_character_monster')
    )
    op.create_table('potion_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('potion_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='check_quantity_non_negative'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['potion_id'], ['potions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'potion_id', name='uq_character_potion')
    )
    op.create_table('pvp_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenger_id', sa.UUID(), nullable=False),
    sa.Column('defender_id', sa.UUID(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=False),
    sa.Column('combat_text', sa.JSON(), nullable=False),
    sa.Column('challenger_damage', sa.Integer(), nullable=False),
    sa.Column('defender_damage', sa.Integer(), nullable=False),
    sa.Column('challenger_rating_change', sa.Integer(), nullable=False),
    sa.Column('defender_rating_change', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenger_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['defender_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_ranking',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 0', name='check_rating_non_negative'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('shop_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('potion_id', sa.UUID(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(item_id IS NOT NULL AND potion_id IS NULL) OR (item_id IS NULL AND potion_id IS NOT NULL)', name='check_item_or_potion'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['potion_id'], ['potions.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('is_unlocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'zone_id', name='uq_check_character_zone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone_progress')
    op.drop_table('shop_listings')
    op.drop_table('pvp_ranking')
    op.drop_table('pvp_matches')
    op.drop_table('potion_inventory')
    op.drop_table('monster_progress')
    op.drop_table('monster_levels')
    op.drop_table('monster_drops')
    op.drop_table('inventory')
    op.drop_table('combat_logs')
    op.drop_table('potions')
    op.drop_table('monsters')
    op.drop_table('items')
    op.drop_table('characters')
    op.drop_table('zones')
    op.drop_table('users')
    # ### end Alembic commands ###
