"""add class_type to items

Revision ID: 8a9c87f66066
Revises: fe93e999468a
Create Date: 2026-03-13 07:15:27.902662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9c87f66066'
down_revision: Union[str, None] = 'fe93e999468a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('class_type', sa.Enum('warrior', 'mage', 'rogue', 'ranger', name='classtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'class_type')
    # ### end Alembic commands ###
