"""add hit_bonus to character

Revision ID: fe93e999468a
Revises: f47b9411f1c0
Create Date: 2026-03-09 20:40:53.023584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe93e999468a'
down_revision: Union[str, None] = 'f47b9411f1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hit_bonus', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'hit_bonus')
    # ### end Alembic commands ###
