from app.core.database import SessionLocal
from app.models.zone import Zone
from app.models.item import Item
from app.core.enums import ItemType, ItemRarity, ClassType


def seed_items(db):
    zone1 = db.query(Zone).filter(Zone.order == 1).first()
    zone2 = db.query(Zone).filter(Zone.order == 2).first()
    zone3 = db.query(Zone).filter(Zone.order == 3).first()
    zone4 = db.query(Zone).filter(Zone.order == 4).first()

    if not all([zone1, zone2, zone3, zone4]):
        raise Exception("Zones must be seeded before items.")

    items = [
        # ==================== ZONE 1 - Whispering Forest ====================
        # --- Shop Items (Common) ---
        {"name": "Ironbark Sword",          "type": ItemType.weapon,    "rarity": ItemRarity.common,    "class_type": ClassType.warrior, "attack_bonus": 4,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Ironbark Breastplate",    "type": ItemType.chest,     "rarity": ItemRarity.common,    "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 20,  "buy_price": 80,   "sell_price": 40,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Ironbark Legguards",      "type": ItemType.legs,      "rarity": ItemRarity.common,    "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 15,  "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Ironbark Helm",           "type": ItemType.head,      "rarity": ItemRarity.common,    "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 10,  "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Ironbark Shield",         "type": ItemType.offhand,   "rarity": ItemRarity.common,    "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 8,   "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Mossveil Staff",          "type": ItemType.weapon,    "rarity": ItemRarity.common,    "class_type": ClassType.mage,    "attack_bonus": 6,  "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Mossveil Robe",           "type": ItemType.chest,     "rarity": ItemRarity.common,    "class_type": ClassType.mage,    "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 15,  "buy_price": 80,   "sell_price": 40,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Mossveil Leggings",       "type": ItemType.legs,      "rarity": ItemRarity.common,    "class_type": ClassType.mage,    "attack_bonus": 1,  "defense_bonus": 1,  "hp_bonus": 12,  "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Mossveil Hood",           "type": ItemType.head,      "rarity": ItemRarity.common,    "class_type": ClassType.mage,    "attack_bonus": 1,  "defense_bonus": 1,  "hp_bonus": 8,   "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Mossveil Tome",           "type": ItemType.offhand,   "rarity": ItemRarity.common,    "class_type": ClassType.mage,    "attack_bonus": 3,  "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Shadowleaf Dagger",       "type": ItemType.weapon,    "rarity": ItemRarity.common,    "class_type": ClassType.rogue,   "attack_bonus": 5,  "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Shadowleaf Vest",         "type": ItemType.chest,     "rarity": ItemRarity.common,    "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 18,  "buy_price": 80,   "sell_price": 40,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Shadowleaf Breeches",     "type": ItemType.legs,      "rarity": ItemRarity.common,    "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 1,  "hp_bonus": 14,  "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Shadowleaf Cowl",         "type": ItemType.head,      "rarity": ItemRarity.common,    "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 1,  "hp_bonus": 10,  "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Shadowleaf Shiv",         "type": ItemType.offhand,   "rarity": ItemRarity.common,    "class_type": ClassType.rogue,   "attack_bonus": 2,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Pinewood Bow",            "type": ItemType.weapon,    "rarity": ItemRarity.common,    "class_type": ClassType.ranger,  "attack_bonus": 4,  "defense_bonus": 0,  "hp_bonus": 5,   "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Pinewood Jerkin",         "type": ItemType.chest,     "rarity": ItemRarity.common,    "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 18,  "buy_price": 80,   "sell_price": 40,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Pinewood Leggings",       "type": ItemType.legs,      "rarity": ItemRarity.common,    "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 1,  "hp_bonus": 14,  "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Pinewood Hood",           "type": ItemType.head,      "rarity": ItemRarity.common,    "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 1,  "hp_bonus": 10,  "buy_price": 60,   "sell_price": 30,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Pinewood Quiver",         "type": ItemType.offhand,   "rarity": ItemRarity.common,    "class_type": ClassType.ranger,  "attack_bonus": 2,  "defense_bonus": 1,  "hp_bonus": 3,   "buy_price": 70,   "sell_price": 35,  "zone_id": zone1.id, "level_requirement": 1},
        {"name": "Woodsman's Charm",        "type": ItemType.accessory, "rarity": ItemRarity.common,    "class_type": None,              "attack_bonus": 1,  "defense_bonus": 1,  "hp_bonus": 8,   "buy_price": 50,   "sell_price": 25,  "zone_id": zone1.id, "level_requirement": 1},
        # --- Drop Items (Uncommon) ---
        {"name": "Thornguard Greatsword",   "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 7,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Thornguard Plate",        "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 5,  "hp_bonus": 30,  "buy_price": 0,    "sell_price": 65,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Thornguard Legguards",    "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 4,  "hp_bonus": 25,  "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Thornguard Helm",         "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 20,  "buy_price": 0,    "sell_price": 50,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Thornguard Shield",       "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 6,  "hp_bonus": 15,  "buy_price": 0,    "sell_price": 60,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Greenwarden Staff",       "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 10, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Greenwarden Robe",        "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 1,  "defense_bonus": 3,  "hp_bonus": 25,  "buy_price": 0,    "sell_price": 65,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Greenwarden Leggings",    "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 1,  "defense_bonus": 2,  "hp_bonus": 20,  "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Greenwarden Hood",        "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 1,  "defense_bonus": 2,  "hp_bonus": 15,  "buy_price": 0,    "sell_price": 50,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Greenwarden Tome",        "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 5,  "defense_bonus": 0,  "hp_bonus": 10,  "buy_price": 0,    "sell_price": 60,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Nightthorn Blade",        "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 9,  "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Nightthorn Vest",         "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 28,  "buy_price": 0,    "sell_price": 65,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Nightthorn Breeches",     "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 22,  "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Nightthorn Cowl",         "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 18,  "buy_price": 0,    "sell_price": 50,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Nightthorn Shiv",         "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 4,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 60,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forestwalker Bow",        "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 7,  "defense_bonus": 0,  "hp_bonus": 5,   "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forestwalker Jerkin",     "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 28,  "buy_price": 0,    "sell_price": 65,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forestwalker Leggings",   "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 22,  "buy_price": 0,    "sell_price": 55,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forestwalker Hood",       "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 2,  "hp_bonus": 18,  "buy_price": 0,    "sell_price": 50,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forestwalker Quiver",     "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 3,  "defense_bonus": 1,  "hp_bonus": 8,   "buy_price": 0,    "sell_price": 60,  "zone_id": zone1.id, "level_requirement": 5},
        {"name": "Forest Talisman",         "type": ItemType.accessory, "rarity": ItemRarity.uncommon,  "class_type": None,              "attack_bonus": 2,  "defense_bonus": 1,  "hp_bonus": 15,  "buy_price": 0,    "sell_price": 45,  "zone_id": zone1.id, "level_requirement": 5},

        # ==================== ZONE 2 - Darkstone Caves ====================
        # --- Shop Items (Uncommon) ---
        {"name": "Stonewall Sword",         "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 10, "defense_bonus": 2,  "hp_bonus": 0,   "buy_price": 200,  "sell_price": 100, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Stonewall Chestplate",    "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 50,  "buy_price": 250,  "sell_price": 125, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Stonewall Legplates",     "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 6,  "hp_bonus": 35,  "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Stonewall Helmet",        "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 5,  "hp_bonus": 28,  "buy_price": 180,  "sell_price": 90,  "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Stonewall Shield",        "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 20,  "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Gloomstone Staff",        "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 15, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 200,  "sell_price": 100, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Gloomstone Robe",         "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 5,  "hp_bonus": 40,  "buy_price": 250,  "sell_price": 125, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Gloomstone Leggings",     "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 3,  "hp_bonus": 28,  "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Gloomstone Cowl",         "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 2,  "hp_bonus": 22,  "buy_price": 180,  "sell_price": 90,  "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Gloomstone Tome",         "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.mage,    "attack_bonus": 7,  "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Obsidian Dagger",         "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 13, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 200,  "sell_price": 100, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Obsidian Vest",           "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 6,  "hp_bonus": 45,  "buy_price": 250,  "sell_price": 125, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Obsidian Breeches",       "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 4,  "hp_bonus": 32,  "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Obsidian Cowl",           "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 25,  "buy_price": 180,  "sell_price": 90,  "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Obsidian Shiv",           "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.rogue,   "attack_bonus": 6,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Bat-hide Bow",            "type": ItemType.weapon,    "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 11, "defense_bonus": 0,  "hp_bonus": 8,   "buy_price": 200,  "sell_price": 100, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Bat-hide Jerkin",         "type": ItemType.chest,     "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 6,  "hp_bonus": 45,  "buy_price": 250,  "sell_price": 125, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Bat-hide Legwraps",       "type": ItemType.legs,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 4,  "hp_bonus": 32,  "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Bat-hide Hood",           "type": ItemType.head,      "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 3,  "hp_bonus": 25,  "buy_price": 180,  "sell_price": 90,  "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Bat-hide Quiver",         "type": ItemType.offhand,   "rarity": ItemRarity.uncommon,  "class_type": ClassType.ranger,  "attack_bonus": 5,  "defense_bonus": 1,  "hp_bonus": 6,   "buy_price": 220,  "sell_price": 110, "zone_id": zone2.id, "level_requirement": 10},
        {"name": "Cave Pendant",            "type": ItemType.accessory, "rarity": ItemRarity.uncommon,  "class_type": None,              "attack_bonus": 2,  "defense_bonus": 1,  "hp_bonus": 20,  "buy_price": 160,  "sell_price": 80,  "zone_id": zone2.id, "level_requirement": 10},
        # --- Drop Items (Rare) ---
        {"name": "Cavern Cleaver",          "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 15, "defense_bonus": 2,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Cavern Chestplate",       "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 12, "hp_bonus": 70,  "buy_price": 0,    "sell_price": 180, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Cavern Legplates",        "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 10, "hp_bonus": 55,  "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Cavern Helmet",           "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 45,  "buy_price": 0,    "sell_price": 145, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Cavern Shield",           "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 30,  "buy_price": 0,    "sell_price": 170, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Voidrock Staff",          "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 22, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Voidrock Robe",           "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 7,  "hp_bonus": 55,  "buy_price": 0,    "sell_price": 180, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Voidrock Leggings",       "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 5,  "hp_bonus": 45,  "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Voidrock Cowl",           "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 4,  "hp_bonus": 35,  "buy_price": 0,    "sell_price": 145, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Voidrock Tome",           "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 10, "defense_bonus": 0,  "hp_bonus": 20,  "buy_price": 0,    "sell_price": 170, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Darkflint Blade",         "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 19, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Darkflint Vest",          "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 60,  "buy_price": 0,    "sell_price": 180, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Darkflint Breeches",      "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 6,  "hp_bonus": 48,  "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Darkflint Cowl",          "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 5,  "hp_bonus": 38,  "buy_price": 0,    "sell_price": 145, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Darkflint Shiv",          "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 8,  "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 170, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Spelunker Bow",           "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 16, "defense_bonus": 0,  "hp_bonus": 8,   "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Spelunker Jerkin",        "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 60,  "buy_price": 0,    "sell_price": 180, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Spelunker Legwraps",      "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 7,  "hp_bonus": 48,  "buy_price": 0,    "sell_price": 160, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Spelunker Hood",          "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 5,  "hp_bonus": 38,  "buy_price": 0,    "sell_price": 145, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Spelunker Quiver",        "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 6,  "defense_bonus": 2,  "hp_bonus": 12,  "buy_price": 0,    "sell_price": 170, "zone_id": zone2.id, "level_requirement": 14},
        {"name": "Cave Crystal",            "type": ItemType.accessory, "rarity": ItemRarity.rare,      "class_type": None,              "attack_bonus": 4,  "defense_bonus": 2,  "hp_bonus": 30,  "buy_price": 0,    "sell_price": 130, "zone_id": zone2.id, "level_requirement": 14},

        # ==================== ZONE 3 - Shattered Ruins ====================
        # --- Shop Items (Rare) ---
        {"name": "Ruinplate Sword",         "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 22, "defense_bonus": 3,  "hp_bonus": 0,   "buy_price": 600,  "sell_price": 300, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Ruinplate Chestplate",    "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 18, "hp_bonus": 90,  "buy_price": 750,  "sell_price": 375, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Ruinplate Legguards",     "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 60,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Ruinplate Helm",          "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 11, "hp_bonus": 50,  "buy_price": 550,  "sell_price": 275, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Ruinplate Shield",        "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 16, "hp_bonus": 35,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Arcane Shard Staff",      "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 32, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 600,  "sell_price": 300, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Arcane Shard Robe",       "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 3,  "defense_bonus": 12, "hp_bonus": 75,  "buy_price": 750,  "sell_price": 375, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Arcane Shard Leggings",   "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 3,  "defense_bonus": 8,  "hp_bonus": 50,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Arcane Shard Hood",       "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 2,  "defense_bonus": 7,  "hp_bonus": 40,  "buy_price": 550,  "sell_price": 275, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Arcane Shard Tome",       "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.mage,    "attack_bonus": 14, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Phantom Dagger",          "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 28, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 600,  "sell_price": 300, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Phantom Vest",            "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 82,  "buy_price": 750,  "sell_price": 375, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Phantom Breeches",        "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 10, "hp_bonus": 55,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Phantom Cowl",            "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 44,  "buy_price": 550,  "sell_price": 275, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Phantom Shiv",            "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.rogue,   "attack_bonus": 12, "defense_bonus": 1,  "hp_bonus": 0,   "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Galeshot Bow",            "type": ItemType.weapon,    "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 24, "defense_bonus": 0,  "hp_bonus": 12,  "buy_price": 600,  "sell_price": 300, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Galeshot Jerkin",         "type": ItemType.chest,     "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 82,  "buy_price": 750,  "sell_price": 375, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Galeshot Legwraps",       "type": ItemType.legs,      "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 10, "hp_bonus": 55,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Galeshot Hood",           "type": ItemType.head,      "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 8,  "hp_bonus": 44,  "buy_price": 550,  "sell_price": 275, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Galeshot Quiver",         "type": ItemType.offhand,   "rarity": ItemRarity.rare,      "class_type": ClassType.ranger,  "attack_bonus": 10, "defense_bonus": 2,  "hp_bonus": 10,  "buy_price": 680,  "sell_price": 340, "zone_id": zone3.id, "level_requirement": 18},
        {"name": "Shard Pendant",           "type": ItemType.accessory, "rarity": ItemRarity.rare,      "class_type": None,              "attack_bonus": 5,  "defense_bonus": 2,  "hp_bonus": 40,  "buy_price": 500,  "sell_price": 250, "zone_id": zone3.id, "level_requirement": 18},
        # --- Drop Items (Epic) ---
        {"name": "Stoneclad Greatsword",    "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 30, "defense_bonus": 4,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Stoneclad Breastplate",   "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 24, "hp_bonus": 120, "buy_price": 0,    "sell_price": 500, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Stoneclad Legguards",     "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 20, "hp_bonus": 95,  "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Stoneclad Helm",          "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 16, "hp_bonus": 80,  "buy_price": 0,    "sell_price": 400, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Stoneclad Bulwark",       "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 28, "hp_bonus": 50,  "buy_price": 0,    "sell_price": 480, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runebound Staff",         "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 42, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runebound Robe",          "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 4,  "defense_bonus": 15, "hp_bonus": 100, "buy_price": 0,    "sell_price": 500, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runebound Leggings",      "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 3,  "defense_bonus": 12, "hp_bonus": 80,  "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runebound Hood",          "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 3,  "defense_bonus": 10, "hp_bonus": 65,  "buy_price": 0,    "sell_price": 400, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runebound Grimoire",      "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 18, "defense_bonus": 0,  "hp_bonus": 35,  "buy_price": 0,    "sell_price": 480, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Wraithstep Blade",        "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 36, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Wraithstep Vest",         "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 18, "hp_bonus": 110, "buy_price": 0,    "sell_price": 500, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Wraithstep Breeches",     "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 88,  "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Wraithstep Cowl",         "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 12, "hp_bonus": 72,  "buy_price": 0,    "sell_price": 400, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Wraithstep Shiv",         "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 15, "defense_bonus": 2,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 480, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Windwalker Bow",          "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 32, "defense_bonus": 0,  "hp_bonus": 15,  "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Windwalker Jerkin",       "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 18, "hp_bonus": 110, "buy_price": 0,    "sell_price": 500, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Windwalker Leggings",     "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 14, "hp_bonus": 88,  "buy_price": 0,    "sell_price": 450, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Windwalker Hood",         "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 12, "hp_bonus": 72,  "buy_price": 0,    "sell_price": 400, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Windwalker Quiver",       "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 10, "defense_bonus": 4,  "hp_bonus": 20,  "buy_price": 0,    "sell_price": 480, "zone_id": zone3.id, "level_requirement": 22},
        {"name": "Runic Amulet",            "type": ItemType.accessory, "rarity": ItemRarity.epic,      "class_type": None,              "attack_bonus": 8,  "defense_bonus": 4,  "hp_bonus": 60,  "buy_price": 0,    "sell_price": 380, "zone_id": zone3.id, "level_requirement": 22},

        # ==================== ZONE 4 - Ember Volcano ====================
        # --- Shop Items (Epic) ---
        {"name": "Emberlord Sword",         "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 40, "defense_bonus": 5,  "hp_bonus": 0,   "buy_price": 1200, "sell_price": 600, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Emberlord Chestplate",    "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 30, "hp_bonus": 150, "buy_price": 1500, "sell_price": 750, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Emberlord Legguards",     "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 24, "hp_bonus": 110, "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Emberlord Helm",          "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 20, "hp_bonus": 90,  "buy_price": 1100, "sell_price": 550, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Emberlord Shield",        "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 28, "hp_bonus": 65,  "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Cinderweave Staff",       "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 55, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 1200, "sell_price": 600, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Cinderweave Robe",        "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 5,  "defense_bonus": 20, "hp_bonus": 120, "buy_price": 1500, "sell_price": 750, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Cinderweave Leggings",    "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 5,  "defense_bonus": 14, "hp_bonus": 90,  "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Cinderweave Hood",        "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 4,  "defense_bonus": 12, "hp_bonus": 75,  "buy_price": 1100, "sell_price": 550, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Cinderweave Tome",        "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.mage,    "attack_bonus": 22, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Ashen Dagger",            "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 48, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 1200, "sell_price": 600, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Ashen Vest",              "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 22, "hp_bonus": 135, "buy_price": 1500, "sell_price": 750, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Ashen Breeches",          "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 16, "hp_bonus": 100, "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Ashen Cowl",              "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 13, "hp_bonus": 82,  "buy_price": 1100, "sell_price": 550, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Ashen Shiv",              "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.rogue,   "attack_bonus": 20, "defense_bonus": 2,  "hp_bonus": 0,   "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Smoldering Bow",          "type": ItemType.weapon,    "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 42, "defense_bonus": 0,  "hp_bonus": 18,  "buy_price": 1200, "sell_price": 600, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Smoldering Jerkin",       "type": ItemType.chest,     "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 22, "hp_bonus": 135, "buy_price": 1500, "sell_price": 750, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Smoldering Legwraps",     "type": ItemType.legs,      "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 16, "hp_bonus": 100, "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Smoldering Hood",         "type": ItemType.head,      "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 13, "hp_bonus": 82,  "buy_price": 1100, "sell_price": 550, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Smoldering Quiver",       "type": ItemType.offhand,   "rarity": ItemRarity.epic,      "class_type": ClassType.ranger,  "attack_bonus": 18, "defense_bonus": 3,  "hp_bonus": 14,  "buy_price": 1350, "sell_price": 675, "zone_id": zone4.id, "level_requirement": 28},
        {"name": "Volcano Heart",           "type": ItemType.accessory, "rarity": ItemRarity.epic,      "class_type": None,              "attack_bonus": 10, "defense_bonus": 5,  "hp_bonus": 75,  "buy_price": 1000, "sell_price": 500, "zone_id": zone4.id, "level_requirement": 28},
        # --- Drop Items (Legendary) ---
        {"name": "Magmaforge Greatsword",   "type": ItemType.weapon,    "rarity": ItemRarity.legendary, "class_type": ClassType.warrior, "attack_bonus": 55, "defense_bonus": 6,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Magmaforge Breastplate",  "type": ItemType.chest,     "rarity": ItemRarity.legendary, "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 40, "hp_bonus": 200, "buy_price": 0,    "sell_price": 950, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Magmaforge Legguards",    "type": ItemType.legs,      "rarity": ItemRarity.legendary, "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 32, "hp_bonus": 160, "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Magmaforge Helm",         "type": ItemType.head,      "rarity": ItemRarity.legendary, "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 26, "hp_bonus": 130, "buy_price": 0,    "sell_price": 850, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Magmaforge Shield",       "type": ItemType.offhand,   "rarity": ItemRarity.legendary, "class_type": ClassType.warrior, "attack_bonus": 0,  "defense_bonus": 45, "hp_bonus": 80,  "buy_price": 0,    "sell_price": 920, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Flamecaller Staff",       "type": ItemType.weapon,    "rarity": ItemRarity.legendary, "class_type": ClassType.mage,    "attack_bonus": 72, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Flamecaller Robe",        "type": ItemType.chest,     "rarity": ItemRarity.legendary, "class_type": ClassType.mage,    "attack_bonus": 6,  "defense_bonus": 25, "hp_bonus": 165, "buy_price": 0,    "sell_price": 950, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Flamecaller Leggings",    "type": ItemType.legs,      "rarity": ItemRarity.legendary, "class_type": ClassType.mage,    "attack_bonus": 5,  "defense_bonus": 20, "hp_bonus": 130, "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Flamecaller Hood",        "type": ItemType.head,      "rarity": ItemRarity.legendary, "class_type": ClassType.mage,    "attack_bonus": 4,  "defense_bonus": 16, "hp_bonus": 105, "buy_price": 0,    "sell_price": 850, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Flamecaller Tome",        "type": ItemType.offhand,   "rarity": ItemRarity.legendary, "class_type": ClassType.mage,    "attack_bonus": 28, "defense_bonus": 0,  "hp_bonus": 55,  "buy_price": 0,    "sell_price": 920, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Scorchblade",             "type": ItemType.weapon,    "rarity": ItemRarity.legendary, "class_type": ClassType.rogue,   "attack_bonus": 62, "defense_bonus": 0,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Scorchblade Vest",        "type": ItemType.chest,     "rarity": ItemRarity.legendary, "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 28, "hp_bonus": 180, "buy_price": 0,    "sell_price": 950, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Scorchblade Breeches",    "type": ItemType.legs,      "rarity": ItemRarity.legendary, "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 22, "hp_bonus": 145, "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Scorchblade Cowl",        "type": ItemType.head,      "rarity": ItemRarity.legendary, "class_type": ClassType.rogue,   "attack_bonus": 0,  "defense_bonus": 18, "hp_bonus": 118, "buy_price": 0,    "sell_price": 850, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Scorchblade Offhand",     "type": ItemType.offhand,   "rarity": ItemRarity.legendary, "class_type": ClassType.rogue,   "attack_bonus": 24, "defense_bonus": 3,  "hp_bonus": 0,   "buy_price": 0,    "sell_price": 920, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Embershot Bow",           "type": ItemType.weapon,    "rarity": ItemRarity.legendary, "class_type": ClassType.ranger,  "attack_bonus": 58, "defense_bonus": 0,  "hp_bonus": 20,  "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Embershot Jerkin",        "type": ItemType.chest,     "rarity": ItemRarity.legendary, "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 28, "hp_bonus": 180, "buy_price": 0,    "sell_price": 950, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Embershot Legwraps",      "type": ItemType.legs,      "rarity": ItemRarity.legendary, "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 22, "hp_bonus": 145, "buy_price": 0,    "sell_price": 900, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Embershot Hood",          "type": ItemType.head,      "rarity": ItemRarity.legendary, "class_type": ClassType.ranger,  "attack_bonus": 0,  "defense_bonus": 18, "hp_bonus": 118, "buy_price": 0,    "sell_price": 850, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Embershot Quiver",        "type": ItemType.offhand,   "rarity": ItemRarity.legendary, "class_type": ClassType.ranger,  "attack_bonus": 20, "defense_bonus": 6,  "hp_bonus": 30,  "buy_price": 0,    "sell_price": 920, "zone_id": zone4.id, "level_requirement": 32},
        {"name": "Ember Core",              "type": ItemType.accessory, "rarity": ItemRarity.legendary, "class_type": None,              "attack_bonus": 14, "defense_bonus": 7,  "hp_bonus": 100, "buy_price": 0,    "sell_price": 850, "zone_id": zone4.id, "level_requirement": 32},
    ]

    for i in items:
        exists = db.query(Item).filter(Item.name == i["name"]).first()
        if not exists:
            db.add(Item(**i))
            print(f"Seeded {i['name']}")
        else:
            print(f"{i['name']} already seeded, skipping...")

    db.commit()


if __name__ == "__main__":
    db = SessionLocal()
    try:
        seed_items(db)
    finally:
        db.close()
